# Generated by Django 4.2.1 on 2023-07-27 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolNombre', models.CharField(max_length=50)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutNumero', models.IntegerField(db_comment='Numero de la ruta del bus')),
                ('rutHorario', models.TextField(db_comment='Hora aproximada en la que pasan los buses')),
                ('rutEmpresa', models.TextField(db_comment='Id de Empresa')),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora del registro')),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True, db_comment='Fecha y hora última actualización')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuNombre', models.CharField(max_length=21)),
                ('usuCorreo', models.CharField(max_length=50)),
                ('usuPassword', models.CharField(max_length=128)),
                ('usuTokenCambioContrasena', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True)),
                ('usuRol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appBussRute.rol')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detLatitud', models.TextField(db_comment='Latitud de la trayectoria de la ruta')),
                ('detLongitud', models.TextField(db_comment='Longitud de la trayectoria de la ruta')),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora del registro')),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True, db_comment='Fecha y hora última actualización')),
                ('detRuta', models.ForeignKey(db_comment='Hace referencia a la ruta que se va a registrar', on_delete=django.db.models.deletion.PROTECT, to='appBussRute.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comDescripcion', models.CharField(max_length=100)),
                ('comValoracion', models.CharField(max_length=30, null=True)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True)),
                ('comUsuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appBussRute.usuario')),
            ],
        ),
    ]
