# Generated by Django 4.2.1 on 2023-06-28 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolNombre', models.CharField(max_length=50)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuNombre', models.CharField(max_length=21)),
                ('usuCorreo', models.CharField(max_length=50)),
                ('usuPassword', models.CharField(max_length=128)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True)),
                ('usuRol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appBussRute.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comDescripcion', models.CharField(max_length=100)),
                ('comValoracion', models.CharField(max_length=30, null=True)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True)),
                ('comUsuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appBussRute.usuario')),
            ],
        ),
    ]
