# Generated by Django 4.2.1 on 2023-10-04 15:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolNombre', models.CharField(max_length=50)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutNumero', models.IntegerField(db_comment='Numero de la ruta del bus', null=True)),
                ('rutPrecio', models.TextField(db_comment='Precio de la Ruta', null=True)),
                ('rutEmpresa', models.TextField(db_comment='Id de Empresa')),
                ('rutEstado', models.CharField(choices=[('A', 'Activa'), ('I', 'Inactiva')], db_comment='Activa y desactiva la ruta', default='A', max_length=1)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora del registro')),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True, db_comment='Fecha y hora última actualización')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuNombre', models.CharField(max_length=21, unique=True)),
                ('usuCorreo', models.CharField(max_length=50, unique=True)),
                ('usuPassword', models.CharField(max_length=128)),
                ('usuCreadoConGoogle', models.BooleanField(default=False)),
                ('usuTokenCambioContrasena', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True)),
                ('usuRol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appBussRute.rol')),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubiBarrio', models.TextField(db_comment='Barrio por donde pasa la ruta')),
                ('ubiComuna', models.TextField(db_comment='Comuna por donde pasa la ruta')),
                ('ubiSitioDeInteres', models.TextField(db_comment='Sitio de interes por donde pasa la ruta')),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora del registro')),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True, db_comment='Fecha y hora última actualización')),
                ('ubiRuta', models.ForeignKey(db_comment='Hace referencia a la ruta que se va a registrar', on_delete=django.db.models.deletion.PROTECT, to='appBussRute.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='FavoritoRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora del registro')),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True, db_comment='Fecha y hora última actualización')),
                ('favRuta', models.ForeignKey(db_comment='Hace referencia a la ruta que se va a añadir a favorito', on_delete=django.db.models.deletion.PROTECT, to='appBussRute.ruta')),
                ('favUsuario', models.ForeignKey(db_comment='Hace referencia al Usuario que añade a favorito', null=True, on_delete=django.db.models.deletion.PROTECT, to='appBussRute.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detLatitud', models.TextField(db_comment='Latitud de la trayectoria de la ruta')),
                ('detLongitud', models.TextField(db_comment='Longitud de la trayectoria de la ruta')),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora del registro')),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True, db_comment='Fecha y hora última actualización')),
                ('detRuta', models.ForeignKey(db_comment='Hace referencia a la ruta que se va a registrar', on_delete=django.db.models.deletion.PROTECT, to='appBussRute.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comDescripcion', models.CharField(max_length=500)),
                ('comValoracion', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True)),
                ('comRuta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appBussRute.ruta')),
                ('comUsuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appBussRute.usuario')),
            ],
        ),
    ]
