# Generated by Django 4.2.1 on 2023-08-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appBussRute", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="usuCreadoConGoogle",
            field=models.BooleanField(default=False),
        ),
    ]