# Generated by Django 4.2 on 2023-06-28 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appBussRute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutNumero', models.IntegerField(db_comment='Numero de la ruta del bus')),
                ('rutHorario', models.TextField(db_comment='Hora aproximada en la que pasan los buses')),
                ('rutEmpresa', models.TextField(db_comment='Id de Empresa')),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora del registro')),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True, db_comment='Fecha y hora última actualización')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detLatitud', models.TextField(db_comment='Latitud de la trayectoria de la ruta')),
                ('detLongitud', models.TextField(db_comment='Longitud de la trayectoria de la ruta')),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora del registro')),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True, db_comment='Fecha y hora última actualización')),
                ('detRuta', models.ForeignKey(db_comment='Hace referencia a la ruta que se va a registrar', on_delete=django.db.models.deletion.PROTECT, to='appBussRute.ruta')),
            ],
        ),
    ]
