# Generated by Django 4.2.1 on 2023-07-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBussRute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token_cambio_contraseña',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
