# Generated by Django 4.2.1 on 2023-07-09 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appBussRute', '0002_usuario_token_cambio_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fechaHoraActualizacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fechaHoraCreacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaHoraActualizacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaHoraCreacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
