# Generated by Django 4.2.1 on 2023-08-23 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appBussRute', '0002_usuario_usucreadocongoogle'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubiBarrio', models.TextField(db_comment='Barrio por donde pasa la ruta')),
                ('ubiComuna', models.TextField(db_comment='Comuna por donde pasa la ruta')),
                ('ubiSitioDeInteres', models.TextField(db_comment='Sitio de interes por donde pasa la ruta')),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora del registro')),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True, db_comment='Fecha y hora última actualización')),
                ('ubiRuta', models.ForeignKey(db_comment='Hace referencia a la ruta que se va a registrar', on_delete=django.db.models.deletion.PROTECT, to='appBussRute.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='FavoritoRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora del registro')),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True, db_comment='Fecha y hora última actualización')),
                ('favRuta', models.ForeignKey(db_comment='Hace referencia a la ruta que se va a añadir a favorito', on_delete=django.db.models.deletion.PROTECT, to='appBussRute.ruta')),
                ('favUsuario', models.ForeignKey(db_comment='Hace referencia al Usuario que añade a favorito', null=True, on_delete=django.db.models.deletion.PROTECT, to='appBussRute.usuario')),
            ],
        ),
    ]
