# Generated by Django 4.2.1 on 2023-08-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBussRute', '0003_ubicacionruta_favoritoruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='comValoracion',
        ),
        migrations.AddField(
            model_name='comentario',
            name='comCalificacion',
            field=models.PositiveIntegerField(choices=[(1, '1 Corazón'), (2, '2 Corazones'), (3, '3 Corazones'), (4, '4 Corazones'), (5, '5 Corazones')], default=5),
        ),
    ]
