# Generated by Django 4.2.1 on 2023-07-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBussRute', '0003_alter_comentario_fechahoraactualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fechaHoraActualizacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fechaHoraCreacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rol',
            name='fechaHoraActualizacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rol',
            name='fechaHoraCreacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaHoraActualizacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaHoraCreacion',
            field=models.DateTimeField(),
        ),
    ]
