# Generated by Django 4.2.1 on 2023-07-09 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBussRute', '0004_alter_comentario_fechahoraactualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fechaHoraActualizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 16, 40, 3, 291706, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fechaHoraCreacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 16, 40, 3, 291706, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rol',
            name='fechaHoraActualizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 16, 40, 3, 290651, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rol',
            name='fechaHoraCreacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 16, 40, 3, 290651, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaHoraActualizacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 16, 40, 3, 291706, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaHoraCreacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 16, 40, 3, 291706, tzinfo=datetime.timezone.utc)),
        ),
    ]
