# Generated by Django 4.2.1 on 2023-08-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBussRute', '0004_remove_comentario_comvaloracion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='comCalificacion',
        ),
        migrations.AddField(
            model_name='comentario',
            name='comValoracion',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
