# Generated by Django 4.2.1 on 2023-08-28 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBussRute', '0005_remove_comentario_comcalificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comValoracion',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
