# Generated by Django 4.2.1 on 2023-08-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBussRute', '0006_alter_comentario_comvaloracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='rutHorario',
        ),
        migrations.AddField(
            model_name='ruta',
            name='rutPrecio',
            field=models.TextField(db_comment='Precio de la Ruta', null=True),
        ),
    ]
