# Generated by Django 4.2.1 on 2023-07-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBussRute', '0006_alter_comentario_fechahoraactualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fechaHoraActualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fechaHoraCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='fechaHoraActualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='fechaHoraCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaHoraActualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaHoraCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
