# Generated by Django 4.2.1 on 2023-08-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBussRute', '0007_remove_ruta_ruthorario_ruta_rutprecio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='rutFoto',
            field=models.FileField(blank=True, null=True, upload_to='rutas/'),
        ),
    ]
