# Generated by Django 4.2.1 on 2023-07-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBussRute', '0007_alter_comentario_fechahoraactualizacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='token_cambio_contraseña',
            new_name='usuTokenCambioContraseña',
        ),
    ]
