# Generated by Django 4.2.1 on 2023-07-16 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBussRute', '0008_rename_token_cambio_contraseña_usuario_usutokencambiocontraseña'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='comDescripcion',
            new_name='comentario',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='comUsuario',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='comValoracion',
            new_name='valoracion',
        ),
    ]
