# Generated by Django 4.2.1 on 2023-09-03 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBussRute', '0008_ruta_rutfoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='rutFoto',
        ),
    ]
