# Generated by Django 4.2.1 on 2023-07-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBussRute', '0009_rename_comdescripcion_comentario_comentario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='comentario',
            new_name='comDescripcion',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='nombre',
            new_name='comUsuario',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='valoracion',
            new_name='comValoracion',
        ),
    ]
