# Generated by Django 4.2.1 on 2023-09-05 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appBussRute', '0009_remove_ruta_rutfoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='comRuta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appBussRute.ruta'),
        ),
    ]
