# Generated by Django 4.2.1 on 2023-07-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBussRute', '0002_ruta_detalleruta'),
        ('appBussRute', '0010_rename_comentario_comentario_comdescripcion_and_more'),
    ]

    operations = [
    ]
