# Generated by Django 4.2.1 on 2023-09-05 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appBussRute', '0012_alter_ruta_rutnumero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comRuta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appBussRute.ruta'),
        ),
    ]
