# Generated by Django 4.2.1 on 2023-09-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBussRute', '0014_alter_usuario_usucorreo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuNombre',
            field=models.CharField(max_length=21, unique=True),
        ),
    ]
