# Generated by Django 4.2.1 on 2023-09-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBussRute', '0015_alter_usuario_usunombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='rutEstado',
            field=models.CharField(choices=[('A', 'Activa'), ('I', 'Inactiva')], db_comment='Activa y desactiva la ruta', default='A', max_length=1),
        ),
    ]
