# Generated by Django 4.2.1 on 2023-09-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBussRute', '0015_alter_usuario_usunombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comDescripcion',
            field=models.CharField(max_length=500),
        ),
    ]
