# Generated by Django 4.2.1 on 2023-09-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBussRute', '0014_alter_comentario_comdescripcion'),
        ('appBussRute', '0016_alter_comentario_comdescripcion'),
        ('appBussRute', '0016_ruta_rutestado'),
    ]

    operations = [
    ]
