# Generated by Django 4.2.1 on 2023-09-21 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBussRute', '0017_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
