# Generated by Django 4.2.1 on 2023-09-23 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBussRute', '0017_merge_20230922_1000'),
        ('appBussRute', '0018_delete_customuser'),
    ]

    operations = [
    ]
